---
# - name: Debug ansible_facts
#   ansible.builtin.debug:
#     var: ansible_facts
#     # e.g. ["ansible_service_mgr"] == "systemd"

- name: Add prosody GPG key and repository
  block:
    - name: Add gpg key
      ansible.builtin.get_url:
        url: https://prosody.im/files/prosody-debian-packages.key
        dest: /etc/apt/trusted.gpg.d/prosody.gpg
        mode: 0644

    - name: Add specified repository into sources list using specified filename
      ansible.builtin.apt_repository:
        repo:
          "deb https://packages.prosody.im/debian \
           {{ ansible_distribution_release }} main"
        state: present
        filename: prosody

- name: Install prosody packages
  ansible.builtin.package:
    name: "{{ prosody_packages }}"
  notify:
    - Restart prosody

- name: Create systemd service file
  ansible.builtin.template:
    src: prosody.service.j2
    dest: /etc/systemd/system/prosody.service
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload systemd
    - Restart prosody
  when:
    - ansible_service_mgr == "systemd"

- name: Configure Prosody
  ansible.builtin.template:
    src: prosody.cfg.lua.j2
    dest: /etc/prosody/prosody.cfg.lua
    owner: root
    group: prosody
    mode: 0640
    backup: true
  notify:
    - Reload systemd
    - Reload prosody config

- name: Include tasks from tls.yml
  ansible.builtin.include_tasks:
    file: tls.yml
    apply:
      tags:
        - certificate
        - cert
        - tls
  tags: always

- name: Create parameters for Diffie–Hellman
  ansible.builtin.command:
    "openssl dhparam \
      -out /etc/prosody/certs/dh-{{ prosody_dhparam_length }}.pem \
       {{ prosody_dhparam_length }}"
  args:
    creates: /etc/prosody/certs/dh-{{ prosody_dhparam_length }}.pem
  notify: Restart prosody

- name: Flush handlers
  ansible.legacy.meta: flush_handlers

- name: Enable prosody systemd service
  ansible.builtin.systemd:
    name: prosody
    enabled: true
  when:
    - ansible_service_mgr == "systemd"

- name: Debug prosody_accounts variable
  ansible.builtin.debug:
    var: prosody_accounts
  tags:
    - user

- name: Create Prosody accounts
  ansible.builtin.shell:
    set -o pipefail;
    printf "%s\n%s\n" "{{ item.password }}" "{{ item.password }}"
    | prosodyctl adduser {{ item.username }}
  with_items: "{{ prosody_accounts }}"
  failed_when: false
  changed_when: false
  no_log: true
  tags:
    - user
    - account
  notify: Reload prosody config
