---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Reload prosody config
  systemd:
    name: prosody
    state: reloaded

- name: Restart prosody
  systemd:
    name: prosody
    state: restarted

- name: Stop prosody
  systemd:
    name: prosody
    state: stopped

- name: Start prosody
  systemd:
    name: prosody
    state: started
