---
- name: Reload systemd
  ansible.legacy.systemd:
    daemon_reload: true

- name: Reload prosody config
  ansible.legacy.systemd:
    name: prosody
    state: reloaded

- name: Restart prosody
  ansible.legacy.service:
    name: prosody
    state: restarted

- name: Stop prosody
  ansible.legacy.service:
    name: prosody
    state: stopped

- name: Start prosody
  ansible.legacy.service:
    name: prosody
    state: started
