---
- name: Converge
  hosts: all
  vars:
    # prosody_vhost: example.com
    prosody_accounts: []
    prosody_certificate_dir: "{{ inventory_dir }}/.tmp"

  tasks:
    - name: "Include sv0.prosody"
      ansible.builtin.include_role:
        name: "sv0.prosody"
