---
- name: Prepare
  hosts: all
  vars:
    prosody_certificate_dir: "{{ inventory_dir }}/.tmp"

  tasks:
    - name: Debug 1
      ansible.builtin.debug:
        var: ansible_distribution_release

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install net-tools (required by testinfa)
      ansible.builtin.apt:
        name: net-tools

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ prosody_certificate_dir }}/{{ prosody_vhost }}"
        state: directory
        mode: 0755
      delegate_to: localhost

    - name: Generate private key
      ansible.builtin.command:
        argv:
          - /bin/openssl genrsa
          - -out
          - "{{ prosody_certificate_dir }}/{{ prosody_vhost }}/privkey.pem"
          - 4096
      changed_when: false
      delegate_to: localhost

    - name: Generate a Self Signed OpenSSL certificate
      ansible.builtin.command:
        argv:
          - /bin/openssl req -new -x509
          - -key
          - "{{ prosody_certificate_dir }}/{{ prosody_vhost }}/privkey.pem"
          - -out
          - "{{ prosody_certificate_dir }}/{{ prosody_vhost }}/fullchain.pem"
          - -days 365
          - -subj
          - "/C=US/ST=Example/L=Example/O=Dis/CN={{ inventory_hostname }}"
      changed_when: false
      delegate_to: localhost
