---
name: Galaxy Action

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows:
      - "Main workflow"
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
